name: Main pipeline with approve with PR
concurrency: ci-${{ github.ref }}
on:
  push:
    branches:
      - dev
  pull_request:

env:
  JAVA_VERSION: "8"
  APP_NAME: hey

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}.x
      - name: Test
        run: java test ./... -cover
      - name: Test race
        run: java test -race ./... -cover
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: deploy/Dockerfile
          push: false
          tags: ${{ env.APP_NAME }}
          build-args: |
            JAVA_VERSION=${{ env.JAVA_VERSION }}
          target: runner
  deploy-dev:
      name: Deploy Dev
      needs: build
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' 
      runs-on: 'ubuntu-latest'
      environment: dev
      steps:
        - name: Deploy dev
          run: echo "Deploying dev"
  deploy-prod:
      name: Deploy prod
      needs: deploy-dev
      runs-on: 'ubuntu-latest'
      timeout-minutes: 15
      environment: 'prod'
      steps:
        - name: Deploy prod
          run: echo "Deploying prod"
